export const AppConstants = {
    Session: {
        ACCESS_TOKEN: 'ACCESS_TOKEN',
        USERID: 'USERID',
        USERNAME: 'USERNAME',
        TIMESECONDS: 'TIMESECONDS',
        CHANGEPASSWORD: 'CHANGEPASSWORD',
        EXPIREDPASSWORD: 'EXPIREDPASSWORD',
        USERROLID: 'ROLID',
        USERROLNAME: 'ROLNAME',
        EMAIL: 'CORREO',
        ACCESS_TOKEN_RIPLEY: 'ACCESS_TOKEN_RIPLEY',
        AGENCYCODE: 'AGENCY_CODE',
        AGENCYNAME: 'AGENCY_NAME',
        SALESCHANNEL: 'SALES_CHANNEL',
        SALES_CHANNEL_DESCRIPTION: 'SALES_CHANNEL_DESCRIPTION',
        FLAG_CANCEL_SOLICITUD: 'FLAG_CANCEL_SOLICITUD',
        CONFIGURATION_BUS: 'CONFIGURATION_BUS',
        SELECT_TOKEN: 'SELECT_TOKEN',
        USERDOCUMENTNUMBER: 'DOCUMENTNUMBER',
        AGENCYCODEFROMT24: 'AGENCYCODEFROMT24',
        TWOFACTOR_REQUIRED: 'TWOFACTOR_REQUIRED',
        TWOFACTOR_ENABLED: 'TWOFACTOR_ENABLED',

        USUARIOLOGIN: "USUARIOLOGIN"
    },
    RolesCode: {
        ADMINISTRADOR: 'R0001',
        GESTOR: 'R0002',
        SUPERVISOR: 'R0003',
        ANALISTA: 'R0004',
        ASESOR: 'R0005',
        CALLCENTER: 'R0006',
        GESTION_USUARIOS: 'R0011',
        PROVEEDORCALLCENTER: 'R0013',
        SUP_CALLCENTER: 'R0014',
        CAJERO_TIENDA: 'R0015',
        SUP_CAJEROTIENDA: 'R0016',
        CAJERO: 'R0018',
        ANALISTA_CREDITOS_SENIOR: 'R0024',
        CONSULTA_SIMULACION: 'R0026',
        SUPERVISOR_IN_BOUND: 'R0038',
        ASESOR_COMERCIAL_SENIOR: 'R0040',
        ASESOR_FINANCIERO_SENIOR: 'R0041',
        JEFE_DE_OPERACIONES: 'R0043',
        GERENTE_DE_AGENCIA: 'R0044',
        ANALISTA_RED_DE_AGENCIA: 'R0046',
        COORDINADOR_DE_VENTAS_EXTERNAS: 'R0047',
        OPERACIONES_EXT_1: 'R0052',
        SUPERVISOR_DE_COLOCACIONES: 'R0053',
        JEFE_DE_CONTROL_INTERNO_DEL_RIESGO: 'R0056',
    },
    TitleModal: {
        CHANGE_PASSWORD: 'Cambiar contraseña.',
    },
    TitleTableHeadAC: {
        COD_PROD: 'cod.',
        DESCRIPCION: 'Descripción',
        LABORATORIO: 'Labora.',
        CANT_UNID_EMPAQUE: 'Cant. Unid. Empaque',
        CONDICION: 'Condición',
        TIPO: 'Tipo',
        PROM_MES: 'Prom. Mes',
        PRE_COMPRA: 'Pre compra',
        COMPRA_FINAL: 'Compra final',
        BONIFICADO: 'Boni',
        ALMACEN: 'Almacén',
        ORGANIZACION: 'Organización',
        CANJE: 'Canje',
        LOGIS_INVER: 'logis_inver',
        OC: 'O/C',
        COBERTURA_ORGANIZACIONAL: 'Cobertura Organizacional',
        MAXI_INFRASTOCK: 'Maximo Infrastock',
        VVF: 'V.V.F',
        VVFNUEVO: 'V.V.F Nuevo',
        DESC1: 'Dsct.1',
        DESC2: 'Dsct.2',
        DESC3: 'Dsct.3',
        DESC4: 'Dsct.4',
        COSCON: 'CosCom',
        PARCIAL: 'Parcial',
        IGV: 'Igv',
        TOTAL: 'Total',
        OBSERVACION: 'Observación',
    },
    TitleTableHeadACAbadi: {
        R: '#R',
        COD_PROD: 'cod.',
        DESCRIPCION: 'Descripción',
        LABORATORIO: 'Labora.',
        ESTABLECIMIENTO: 'Establecimiento',
        CANT_UNID_EMPAQUE: 'Cant. Unid. Empaque',
        CONDICION: 'Condición',
        PROM_MES: 'Prom. Mes',
        PRE_COMPRA: 'Pre compra',
        COMPRA_FINAL: 'Compra final',
        BONIFICADO: 'Boni',
        BOTICA: 'Botica',
        OCVIGENTE: 'O/C Vigente',
        OCVENCIDA: 'O/C Vencida',
        OC: 'OC',
        BOTICAOC: 'Botica + OC',
        COBERTURA_BOTICA: 'Cobertura Botica (Dia)',
        OBSERVACION: 'Observación',
    },

    TitleTableHeadUC: {
        PROVEEDOR: 'Proveedor',
        S_ORDEN: 'S - Orden',
        FECHA: 'Fecha',
        CANT_E: 'Cant.-E',
        CANT_F: 'Cant.- F',
        VVF: 'V.V.F',
        DESC1: 'Dscto1(%)',
        DESC2: 'Dscto2(%)',
        DESC3: 'Dscto3(%)',
        DESC4: 'Dscto4(%)',
        BONI: 'Boni',
    },
    TitleTableHeadUI:{
      INVRUM:'Invnum',
      PROVEEDOR:'Proveedor',
      DOCUMENTO:'Documento',
      FECHA_INGRESO:'Fecha de ingreso',
      ORDEN_COMPRA:'Orden de Compra',
      CANT_E:'Cant.-E',
      CANT_F:'Cant.-F',
      VVF:'V.V.F',
      DESC1:'Dsct1(%)',
      DESC2:'Dsct2(%)',
      DESC3:'Dsct3(%)',
      DESC4:'Dsct4(%)',
      BONI:'Boni',
    },
    DetalleStockBotica:{
        DETALLESTOCKBOTICA:1,
        DETALLEINFRASTOCK:2
    },
    TtitleHeadGOC:{
        INDEX:'index',
        CODIGO:'Código',
        DESCRIPCION:'Descripción',
        LABORATORIO:'Laboratorio',
        CANT:'Cant.',
        BONI:'Boni',
        VVF:'V.V.F',
        VVFNUEVO:'V.V.F Nuevo',
        DESCT1:'Desct.1',
        DESCT2:'Desct.2',
        DESCT3:'Desct.3',
        DESCT4:'Desct.4',
        COSCOM:'CosCom',
        PARCIAL:'Parcial',
        IGV:'Igv',
        TOTAL:'Total',
    }

}
